### ISSUE TITLE
Move edge-agent logic to agent-sdk

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/agent-sdk#23]
Idea is to create simplified APIs that can be used by sdk, browser(js/wasm binding), mobile native(gomobile), rest bindings for the business logic present in edge-agent (currently, it's written in Javascript). Instead of repeating these in individual bindings, we need to move the JS code to Golang code and expose them through different bindings.

The list includes
- wallet login (create DID, register with mediator)
- DIDComm/AuthZ logic with issuer/rp
- etc

**Comment by sudeshrshetty** [comment]
### Modules identified by wallet implementations
Reference: [edge-agent wallet implementation](https://github.com/trustbloc/edge-agent/tree/master/cmd/user-agent/src/pages/chapi/wallet)

1. **Presentation Exchange** - expected to be part of [aries-framework-go](https://github.com/hyperledger/aries-framework-go) 
2. **Blinded Routing** - to be implemented in agent-sdk as a new command package
3. **Mediator Client** - All [generic mediator client logic](https://github.com/trustbloc/edge-agent/blob/master/cmd/user-agent/src/pages/chapi/wallet/didcomm/mediator.js) required by wallet
4. **DID Manager** - Portion of [this](https://github.com/trustbloc/edge-agent/blob/master/cmd/user-agent/src/pages/chapi/wallet/didmgmt/didManager.js) can be moved to agent-sdk only if required(very unlikely)
5. **Get credential by query** - AuthZ, credential search logics to be moved to agent-sdk from [wallet implementation](https://github.com/trustbloc/edge-agent/blob/master/cmd/user-agent/src/pages/chapi/wallet/get/getCredentialsByQuery.js)
6. **Wallet Registration & on-boarding** - portion of [this wallet implementation ](https://github.com/trustbloc/edge-agent/blob/master/cmd/user-agent/src/pages/chapi/wallet/register/register.js)can be moved to agent-sdk if required(very unlikely)

**Comment by sudeshrshetty** [comment]
Tasks
- [ ] mediator client #56 
- [ ] blinded routing 
- [ ] DID Manager
- [ ] Get Credentials
- [ ] Presentation Exchange
- [ ] Wallet Registration
- [ ] Wallet Storage
