### ISSUE TITLE
[OpenID4VP] Implement OIDC Initiate Presentation API in wallet-sdk

### ISSUE THREAD

**Issue by birtony** [trustbloc/agent-sdk#432]

**Comment by rolsonquadras** [comment]
At high level, here is the logic:

- Retrieve [JWT token with Presentation Exchange ](https://identity.foundation/jwt-vc-presentation-profile/#self-issued-op-request-object)by calling the [url from the input](url https://identity.foundation/jwt-vc-presentation-profile/#self-issued-op-request-uri)
- Validate the JWT token
- Validate the Well Known DID Configuration
- Extract Presentation Definition query
